### PR TITLE
Docs added for celo-composer

### PR DESCRIPTION
**Pull request by viral-sangani**
Created Sample docs for Celo Composer. 
Added a few basic pages like Introduction, getting started pages, etc. We need to add framework/tools-specific pages.

Let's all work in this branch `docs` and build it together.
cc. @Ernesto-tha-great @joenyzio @alofeoluwafemi @therealharpaljadeja @nestorbonilla

### CODE REVIEW

**Comment by viral-sangani** [comment]
Let's share the framework and tools section for docs. We can take the framework we have worked on or are most familiar with and write that section of the docs.

**Comment by alofeoluwafemi** [comment]
@therealharpaljadeja, do you want us to start the contribution after PR is merged or proceed regardless? What's your plan?

**Comment by viral-sangani** [comment]
@alofeoluwafemi I was hoping we could deploy the docs once we fill all the framework pages. Because merging empty pages doesn't seem reasonable.

**Comment by nestorbonilla** [comment]
Closing PR for outdated. If it needs to be re-opened, please feel free to do it.

**Pull request closed without merging**
