### PR TITLE
Add Pinata Integration

### PR DESCRIPTION
**Pull request by Ankush263**
I add Pinata integration as an example.

### CODE REVIEW

**Comment by viral-sangani** [comment]
@Ankush263 Hey, thank you so much for the PR. Can you please add some description on how one can use this?

**Comment by nestorbonilla** [comment]
Hi @Ankush263, thanks for the PR; as @viral-sangani mentioned, please add more description.
I think [Celo Examples](https://github.com/celo-example) could interest you in this particular case.
Closing PR in the meantime.

**Comment by Ankush263** [comment]
@nestorbonilla  @viral-sangani  I add some descriptions as you mention. Let me know if anything else is required..

**Comment by nestorbonilla** [comment]
Hi @Ankush263, thanks for the update. This suggestion fits better under [celo-examples](https://github.com/celo-example) as a complete example, given that there are many IPFS pining services, and Pinata is just one of them.
Would you like to create an example on [celo-examples](https://github.com/celo-example)?

**Comment by Ankush263** [comment]
sure, should I make a PR in [celo-composer-react-example](https://github.com/celo-example/celo-composer-react-example) repo ...??? @nestorbonilla

**Pull request closed without merging**
