### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by aditya98**
Added the Alternate Truffle version for deploying and testing smart contracts instead of hardhat

### CODE REVIEW

**Comment by aditya98** [comment]
Alternate development of Celo Dapp using truffle framework

**Comment by aditya98** [comment]
Sure, I'd love to do that.

**Comment by critesjosh** [comment]
Great! Do you want to keep working on this in this PR?

**Comment by nestorbonilla** [comment]
Closing PR for outdated.

**Pull request closed without merging**
