### PR TITLE
Sync composer docs from Gitbook to Github

### PR DESCRIPTION
**Pull request by alofeoluwafemi**
Docs is hosted on https://celo-composer.gitbook.io/docs/. @therealharpaljadeja  @joenyzio

### CODE REVIEW

**Comment by viral-sangani** [comment]
@alofeoluwafemi It seems the docs are quite outdated. Need to update the docs before we can merge it.
Some suggestions on top of my mind - 
- In the installation section, instead is cloning the repo, need to add CLI.
- In the supported framework need to add Angular and truffle
- Need to remove the empty pages or at least add some content.
- Can create a section like a showcase - Projects built with Celo Composer. (We are working on a list of Celo composer examples - [https://github.com/organizations/celo-example](https://github.com/organizations/celo-example))
- Add React Advance and React Black boilerplate in the docs.

There are some other features that we can add in docs. Happy to help and share the workload. 
Let me know if you need any more information or want to schedule a call for this.

**Comment by alofeoluwafemi** [comment]
@viral-sangani, yes I agree we should have a session to plan this out better. I was of the opinion of merging first before I improve the installation process. I will do a follow-up chat on discord

**Comment by viral-sangani** [comment]
@alofeoluwafemi Had a chat with Eric about this; since we are going to add a lot of new docs for the composer, can we go with Docusaurus instead of Gitbook since we are already using Docusaurus for Celo docs.

**Comment by nestorbonilla** [comment]
Closing PR for outdated. If it needs to be re-opened, please feel free to do it.

**Pull request closed without merging**
